/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import modelPath from '../../assets/IridescenceLamp.glb'

export default function Lamp(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(modelPath)

  return (
    <group ref={group} {...props}>
      <mesh material={materials.IridescenceLampIridescence} geometry={nodes.lamp_iridescence.geometry} />
    </group>
  )
}

useGLTF.preload('/IridescenceLamp.gltf')
