/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/IridescenceLamp.glb')
  return (
    <group ref={group} {...props}>
      <mesh material={materials.IridescenceLamp} geometry={nodes.lamp.geometry} />
      <mesh material={materials.IridescenceLampTransmissionIridescence} geometry={nodes.lamp_transmission.geometry} />
      <mesh material={materials.IridescenceLampIridescence} geometry={nodes.lamp_iridescence.geometry} />
    </group>
  )
}

useGLTF.preload('/IridescenceLamp.glb')
