/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import RockPlatformPath from '../../assets/RockPlatform.glb'
import useIridescentMaterial from '../../utils/useIridescentMaterial'

function RockPlatform(props) {
  const group = useRef()
  const { nodes } = useGLTF(RockPlatformPath)
  const iridescentMaterial = useIridescentMaterial('green')

  return (
    <group ref={group} {...props}>
      <mesh
        material={iridescentMaterial}
        geometry={nodes.Grock2.geometry}
        position={[-0.01, -0.19, -0.05]}
        rotation={[Math.PI / 2, 0, -3]}
        scale={[0.06, 0.06, 0.03]}
        castShadow={true}
        receiveShadow={true}
      />
    </group>
  )
}

export default RockPlatform

useGLTF.preload(RockPlatformPath)
